source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

# base
gem 'rails', '~> 5.2.0'
# db

gem 'mysql2', '>= 0.4.4', '< 0.6.0'

# server
gem 'puma', '~> 3.11'

# view
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
# 手動追加
gem 'bootstrap', '~> 4.1', '>= 4.1.1'
gem 'jquery-rails', '~> 4.3', '>= 4.3.3'
gem 'popper_js', '~> 1.12', '>= 1.12.9'
gem 'tether-rails', '~> 1.4'

# 認証
gem 'devise', '~> 4.4', '>= 4.4.3'

# json
gem 'jbuilder', '~> 2.5'

# 非同期
gem 'sidekiq', '~> 5.1', '>= 5.1.3'

# boot
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  # 手動追加
  gem 'better_errors', '~> 2.4'
  gem 'binding_of_caller', '~> 0.8.0'
  gem 'rubocop', '~> 0.56.0'
  gem 'annotate', '~> 2.7', '>= 2.7.3'
  gem 'overcommit', '~> 0.45.0'
end

group :test do
  # 手動追加
  gem 'rspec-rails', '~> 3.7', '>= 3.7.2'
  gem 'factory_bot_rails', '~> 4.10'
  gem 'database_cleaner', '~> 1.7'
end
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
